version: "3"
services:
  app:
    build: ./docker/app
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/nginx.conf
      - ./src/backend:/var/www/backend
      - ./src/frontend:/var/www/frontend
      - ./startup:/var/www/startup
      # nginx エラーログのマウント
      - ./log:/var/log/nginx
    ports:
      - "3031:80"
    environment:
      TZ: "Asia/Tokyo"
